//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./postServices_types');
//HELPER FUNCTIONS AND STRUCTURES

var PostService_addPost_args = function(args) {
  this.title = null;
  this.content = null;
  this.tag = null;
  if (args) {
    if (args.title !== undefined && args.title !== null) {
      this.title = args.title;
    }
    if (args.content !== undefined && args.content !== null) {
      this.content = args.content;
    }
    if (args.tag !== undefined && args.tag !== null) {
      this.tag = args.tag;
    }
  }
};
PostService_addPost_args.prototype = {};
PostService_addPost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.title = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.content = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.tag = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_addPost_args.prototype.write = function(output) {
  output.writeStructBegin('PostService_addPost_args');
  if (this.title !== null && this.title !== undefined) {
    output.writeFieldBegin('title', Thrift.Type.STRING, 1);
    output.writeString(this.title);
    output.writeFieldEnd();
  }
  if (this.content !== null && this.content !== undefined) {
    output.writeFieldBegin('content', Thrift.Type.STRING, 2);
    output.writeString(this.content);
    output.writeFieldEnd();
  }
  if (this.tag !== null && this.tag !== undefined) {
    output.writeFieldBegin('tag', Thrift.Type.STRING, 3);
    output.writeString(this.tag);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostService_addPost_result = function(args) {
};
PostService_addPost_result.prototype = {};
PostService_addPost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_addPost_result.prototype.write = function(output) {
  output.writeStructBegin('PostService_addPost_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostService_getPost_args = function(args) {
  this.title = null;
  if (args) {
    if (args.title !== undefined && args.title !== null) {
      this.title = args.title;
    }
  }
};
PostService_getPost_args.prototype = {};
PostService_getPost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.title = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_getPost_args.prototype.write = function(output) {
  output.writeStructBegin('PostService_getPost_args');
  if (this.title !== null && this.title !== undefined) {
    output.writeFieldBegin('title', Thrift.Type.STRING, 1);
    output.writeString(this.title);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostService_getPost_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Post(args.success);
    }
  }
};
PostService_getPost_result.prototype = {};
PostService_getPost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Post();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_getPost_result.prototype.write = function(output) {
  output.writeStructBegin('PostService_getPost_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostService_delPost_args = function(args) {
  this.title = null;
  if (args) {
    if (args.title !== undefined && args.title !== null) {
      this.title = args.title;
    }
  }
};
PostService_delPost_args.prototype = {};
PostService_delPost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.title = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_delPost_args.prototype.write = function(output) {
  output.writeStructBegin('PostService_delPost_args');
  if (this.title !== null && this.title !== undefined) {
    output.writeFieldBegin('title', Thrift.Type.STRING, 1);
    output.writeString(this.title);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostService_delPost_result = function(args) {
};
PostService_delPost_result.prototype = {};
PostService_delPost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PostService_delPost_result.prototype.write = function(output) {
  output.writeStructBegin('PostService_delPost_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PostServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
PostServiceClient.prototype = {};
PostServiceClient.prototype.seqid = function() { return this._seqid; };
PostServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
PostServiceClient.prototype.addPost = function(title, content, tag, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_addPost(title, content, tag);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_addPost(title, content, tag);
  }
};

PostServiceClient.prototype.send_addPost = function(title, content, tag) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('addPost', Thrift.MessageType.CALL, this.seqid());
  var params = {
    title: title,
    content: content,
    tag: tag
  };
  var args = new PostService_addPost_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PostServiceClient.prototype.recv_addPost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new PostService_addPost_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
PostServiceClient.prototype.getPost = function(title, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getPost(title);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getPost(title);
  }
};

PostServiceClient.prototype.send_getPost = function(title) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getPost', Thrift.MessageType.CALL, this.seqid());
  var params = {
    title: title
  };
  var args = new PostService_getPost_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PostServiceClient.prototype.recv_getPost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new PostService_getPost_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getPost failed: unknown result');
};
PostServiceClient.prototype.delPost = function(title, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_delPost(title);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_delPost(title);
  }
};

PostServiceClient.prototype.send_delPost = function(title) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('delPost', Thrift.MessageType.CALL, this.seqid());
  var params = {
    title: title
  };
  var args = new PostService_delPost_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PostServiceClient.prototype.recv_delPost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new PostService_delPost_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var PostServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
PostServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
PostServiceProcessor.prototype.process_addPost = function(seqid, input, output) {
  var args = new PostService_addPost_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.addPost.length === 3) {
    Q.fcall(this._handler.addPost.bind(this._handler), args.title, args.content, args.tag)
      .then(function(result) {
        var result_obj = new PostService_addPost_result({success: result});
        output.writeMessageBegin("addPost", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("addPost", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.addPost(args.title, args.content, args.tag, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new PostService_addPost_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("addPost", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("addPost", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
PostServiceProcessor.prototype.process_getPost = function(seqid, input, output) {
  var args = new PostService_getPost_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getPost.length === 1) {
    Q.fcall(this._handler.getPost.bind(this._handler), args.title)
      .then(function(result) {
        var result_obj = new PostService_getPost_result({success: result});
        output.writeMessageBegin("getPost", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getPost", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getPost(args.title, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new PostService_getPost_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getPost", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getPost", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
PostServiceProcessor.prototype.process_delPost = function(seqid, input, output) {
  var args = new PostService_delPost_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.delPost.length === 1) {
    Q.fcall(this._handler.delPost.bind(this._handler), args.title)
      .then(function(result) {
        var result_obj = new PostService_delPost_result({success: result});
        output.writeMessageBegin("delPost", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("delPost", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.delPost(args.title, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new PostService_delPost_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("delPost", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("delPost", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
